# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
	. ~/.bashrc
fi

# User specific environment and startup programs

export JAVA_HOME=/usr/lib/jvm/default-java
export EC2_HOME=/usr/local/bin/ec2-api-tools
export EC2_AMITOOL_HOME=/usr/local/bin/ec2-ami-tools

PATH=$PATH:$HOME/bin:$EC2_HOME/bin:$EC2_AMITOOL_HOME/bin
export PATH


PS1='\[\033[01;31m\]\h\[\033[01;34m\] \W \$\[\033[00m\] '

export HISTFILESIZE=50000
export HISTSIZE=50000
export HISTCONTROL=ignoreboth
export EXTENDED_HISTORY=ON
export HISTTIMEFORMAT="[%c]  "


# AWS tools access
export AWS_ACCESS_KEY=AKIAIUBY2AWXMSEP5ZLQ
export AWS_SECRET_KEY=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
export EC2_URL=https://ec2.us-west-2.amazonaws.com 
